<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte';
  import { ArrowLeft, ArrowRight, Eye, Plus, Save, Trash2, X } from '@lucide/svelte';
  import { api } from '$lib/api/client';
  import AdminRichText from './AdminRichText.svelte';
  import MediaPicker from './MediaPicker.svelte';
  import AdminLodgeMedia from './AdminLodgeMedia.svelte';
  import Section from './accommodation/Section.svelte';
  import Field from './accommodation/Field.svelte';
  import Select from './accommodation/Select.svelte';
  import Text from './accommodation/Text.svelte';
  import Check from './accommodation/Check.svelte';
  import Chips from './accommodation/Chips.svelte';
  import Card from './accommodation/Card.svelte';
  import Repeater from './accommodation/Repeater.svelte';
  import RoomImages from './accommodation/RoomImages.svelte';
  import { ACCESSIBILITY, AMENITIES, BED_TYPES, BEST_FOR, ELECTRICITY, MEAL_PLANS, MOBILE_NETWORKS, PRICING_BASES, PROPERTY_CATEGORIES, PROPERTY_TYPES, ROAD_ACCESS, ROOM_TYPES, ROOM_VIEWS, SEASON_TYPES, SETTINGS, SUPPLIER_PREFERENCES, WIFI } from '$lib/accommodationEnums';

  export let editing: Record<string, any> | null = null;
  export let destinations: Array<{label:string;value:string}> = [];
  const dispatch=createEventDispatcher<{close:void;saved:string}>();
  const steps=['Basics','Travel Profile','Location','Rooms','Rates','Amenities & Experiences','Gallery','Supplier','Related Tours','SEO','Review & Publish'];
  const months=['January','February','March','April','May','June','July','August','September','October','November','December'];
  const roomAmenities=AMENITIES;
  let step=0,saving=false,error='',dirty=false,savedId=editing?.id??'', mediaEditor:AdminLodgeMedia;
  let tours:Array<any>=[],lodges:Array<any>=[],experienceOptions:Array<any>=[],supplierOptions:Array<any>=[];
  let details:any={highlights:[],rooms:[],rates:[],inclusions:[],supplier:{},destination_ids:[],tour_ids:[],alternative_ids:[],experience_ids:[]};
  let form:any={name:'',slug:'',destination_id:'',short_description:'',description:'',why_we_recommend:'',accommodation_level:'MID_RANGE',lodge_type:'SAFARI_LODGE',status:'draft',is_featured:false,best_for:[],settings:[],recommended_nights:'',best_months:[],google_maps_url:'',latitude:'',longitude:'',transfer_time:'',distance_airstrip:'',distance_park_gate:'',road_accessibility:'',fly_in_available:false,transfer_available:false,hero_image_url:'',image_url:'',mobile_hero_image_url:'',children_allowed:true,minimum_child_age:'',family_friendly:false,honeymoon_friendly:false,accessibility:'UNKNOWN',electricity_availability:'',wifi_availability:'',mobile_networks:[],wheelchair_accessible:false,show_rates_publicly:false,show_property_publicly:true,arrival_instructions:'',traveler_notes:'',seo_title:'',meta_description:'',social_image_url:'',indexable:true,currency:'USD'};
  const human=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
  const toggle=(key:string,value:string)=>{const list=form[key]??[];form={...form,[key]:list.includes(value)?list.filter((x:string)=>x!==value):[...list,value]};dirty=true};
  const toggleDetail=(key:string,value:string)=>{const list=details[key]??[];details={...details,[key]:list.includes(value)?list.filter((x:string)=>x!==value):[...list,value]};dirty=true};
  const addHighlight=()=>details={...details,highlights:[...details.highlights,{title:''}]};
  const addRoom=()=>details={...details,rooms:[...details.rooms,{name:'',room_type:'STANDARD_ROOM',short_description:'',max_adults:2,max_children:0,max_guests:2,bed_types:[],unit_count:1,views:[],amenities:[],images:[]}]};
  const addRate=()=>details={...details,rates:[...details.rates,{season_type:'HIGH_SEASON',season_name:'',valid_from:'',valid_until:'',currency:form.currency||'USD',rack_rate:null,net_rate:null,single_rate:null,double_rate:null,triple_rate:null,child_rate:null,single_supplement:null,pricing_basis:'PER_PERSON_SHARING',meal_plan:'FULL_BOARD'}]};
  const addItem=(included:boolean)=>details={...details,inclusions:[...details.inclusions,{title:'',is_included:included}]};
  const removeAt=(key:string,index:number)=>details={...details,[key]:details[key].filter((_:any,i:number)=>i!==index)};
  const toggleExperience=(name:string)=>{const x=experienceOptions.find(x=>x.name===name);if(x)toggleDetail('experience_ids',x.id)};
  const toggleRelation=(key:string,rows:any[],labelKey:string,name:string)=>{const x=rows.find(x=>x[labelKey]===name);if(x)toggleDetail(key,x.id)};
  const toggleDestination=(name:string)=>{const x=destinations.find(x=>x.label===name);if(x)toggleDetail('destination_ids',x.value)};
  const removeInclusion=(included:boolean,index:number)=>{const rows=details.inclusions.filter((x:any)=>x.is_included===included);const target=rows[index];details={...details,inclusions:details.inclusions.filter((x:any)=>x!==target)}};
  const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const payload=()=>Object.fromEntries(Object.entries(form).map(([k,v])=>[k,v===''?null:v]));
  const save=async(exit=false)=>{if(!form.name.trim()){error='Property name is required.';step=0;return} saving=true;error='';try{form.slug=form.slug||slugify(form.name);const res=savedId?await api.lodges.update(savedId,payload()):await api.lodges.create(payload());savedId=String((res.data as any).id||savedId);await api.lodges.saveDetails(savedId,{...details,rooms:details.rooms.map((r:any)=>({...r,images:r.images??r.lodge_room_images??[]}))});await mediaEditor?.save(savedId);dirty=false;localStorage.removeItem('accommodation-draft');dispatch('saved',savedId);if(exit)dispatch('close')}catch(e){error=e instanceof Error?e.message:'Unable to save property.'}finally{saving=false}};
  const beforeUnload=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};
  $: if(!editing&&!form.slug) form.slug=slugify(form.name);
  $: if(dirty&&typeof localStorage!=='undefined') localStorage.setItem('accommodation-draft',JSON.stringify({form,details,step}));
  onMount(()=>{window.addEventListener('beforeunload',beforeUnload);void(async()=>{if(editing){form={...form,...editing,best_for:editing.best_for??[],best_months:editing.best_months??[],settings:editing.settings??[],mobile_networks:editing.mobile_networks??[]};const d=await api.lodges.details(editing.id).catch(()=>null);if(d?.data){details={...details,...d.data,supplier:d.data.supplier??{}};details.rooms=(details.rooms??[]).map((room:any)=>({...room,images:room.images??room.lodge_room_images??[]}))}void mediaEditor?.load(editing.id)}else{const draft=localStorage.getItem('accommodation-draft');if(draft){try{const d=JSON.parse(draft);form={...form,...d.form};details={...details,...d.details};step=d.step??0}catch{}}void mediaEditor?.load(null)}const [tr,lr,mr]=await Promise.allSettled([api.tours.list({status:'published',limit:200}),api.lodges.list({status:'all',limit:200}),api.lodges.accommodationMeta()]);if(tr.status==='fulfilled')tours=tr.value.data.items;if(lr.status==='fulfilled')lodges=lr.value.data.items.filter((x:any)=>x.id!==editing?.id);if(mr.status==='fulfilled'){experienceOptions=mr.value.data.experiences??[];supplierOptions=mr.value.data.suppliers??[]}})();return()=>window.removeEventListener('beforeunload',beforeUnload)});
</script>

<div class="fixed inset-0 z-[180] bg-black/50 p-0 backdrop-blur-sm md:p-4">
  <div class="mx-auto flex h-full w-full max-w-6xl flex-col overflow-hidden bg-canvas shadow-2xl md:h-[94vh] md:rounded-[14px]">
    <header class="flex items-center gap-4 border-b border-ink/10 bg-surface px-4 py-3 md:px-6">
      <div class="min-w-0 flex-1"><p class="text-[10px] font-bold uppercase tracking-[.16em] text-forest/70">Accommodation CMS</p><h2 class="truncate text-xl font-bold text-heading">{editing?'Edit property':'New property'}</h2></div>
      {#if savedId}<a class="hidden h-10 items-center gap-2 rounded-lg border border-ink/10 px-4 text-sm font-bold md:inline-flex" href={`/accommodation/${form.slug}`} target="_blank"><Eye size={15}/> Preview</a>{/if}
      <button class="grid h-10 w-10 place-items-center rounded-lg border border-ink/10" type="button" aria-label="Close" on:click={()=>dispatch('close')}><X size={18}/></button>
    </header>
    <nav class="no-scrollbar flex shrink-0 gap-1 overflow-x-auto border-b border-ink/10 bg-surface px-3 py-2 md:px-6">
      {#each steps as label,i}<button type="button" on:click={()=>step=i} class={`whitespace-nowrap rounded-full px-3 py-2 text-xs font-bold ${step===i?'bg-deep-green text-white':'text-ink/55 hover:bg-sand'}`}>{i+1}. {label}</button>{/each}
    </nav>
    <form class="flex min-h-0 flex-1 flex-col" on:input={()=>dirty=true} on:change={()=>dirty=true} on:submit|preventDefault={()=>save(false)}>
      <div class="min-h-0 flex-1 overflow-y-auto p-4 md:p-7">
        {#if error}<p class="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>{/if}
        <div class="mx-auto max-w-4xl space-y-5">
          {#if step===0}<Section title="Basic Information" note="The essentials travelers and itinerary planners need."><div class="grid gap-4 md:grid-cols-2"><Field label="Property name" bind:value={form.name} required/><Field label="URL slug" bind:value={form.slug}/><Select label="Property type" bind:value={form.lodge_type} options={PROPERTY_TYPES}/><Select label="Category" bind:value={form.accommodation_level} options={PROPERTY_CATEGORIES}/><Select label="Primary destination" bind:value={form.destination_id} options={destinations.map(x=>x.value)} labels={Object.fromEntries(destinations.map(x=>[x.value,x.label]))}/></div><Text label="Short description" bind:value={form.short_description}/><AdminRichText label="Full description" name="description" bind:value={form.description} rows={7}/><div class="grid gap-4 md:grid-cols-3"><Select label="Status" bind:value={form.status} options={['draft','published','hidden','archived']} labels={{draft:'Draft',published:'Published',hidden:'Hidden',archived:'Archived'}}/><Check label="Featured" bind:checked={form.is_featured}/><Check label="Show property publicly" bind:checked={form.show_property_publicly}/></div></Section>
          {:else if step===1}<Section title="Travel Profile" note="Position the stay for the right traveler and season."><Chips label="Best for" options={BEST_FOR} selected={form.best_for} onToggle={(x)=>toggle('best_for',x)}/><Chips label="Property setting" options={SETTINGS} selected={form.settings} onToggle={(x)=>toggle('settings',x)}/><Field label="Recommended nights" type="number" bind:value={form.recommended_nights}/><Chips label="Best months" options={months} selected={form.best_months} onToggle={(x)=>toggle('best_months',x)}/><Repeater title="Property highlights" items={details.highlights} add={addHighlight} remove={(i)=>removeAt('highlights',i)} field="title"/></Section>
          {:else if step===2}<Section title="Location & Logistics" note="Only operational details used while building itineraries."><div class="grid gap-4 md:grid-cols-2"><Field label="Google Maps URL" bind:value={form.google_maps_url}/><Field label="Latitude" type="number" bind:value={form.latitude}/><Field label="Longitude" type="number" bind:value={form.longitude}/><Field label="Transfer time" bind:value={form.transfer_time}/><Field label="Distance from airstrip" bind:value={form.distance_airstrip}/><Field label="Distance from park gate" bind:value={form.distance_park_gate}/><Select label="Road accessibility" bind:value={form.road_accessibility} options={ROAD_ACCESS}/></div><div class="grid gap-3 md:grid-cols-2"><Check label="Fly-in available" bind:checked={form.fly_in_available}/><Check label="Transfer available" bind:checked={form.transfer_available}/></div></Section>
          {:else if step===3}<Section title="Rooms / Units" note="Simple room profiles—not inventory or availability management."><button class="add" type="button" on:click={addRoom}><Plus size={15}/> Add room type</button>{#each details.rooms as room,i}<Card title={`Room ${i+1}`} remove={()=>removeAt('rooms',i)}><div class="grid gap-3 md:grid-cols-2"><Field label="Display name" bind:value={room.name}/><Select label="Room type" bind:value={room.room_type} options={ROOM_TYPES}/><Field label="Number of units" type="number" bind:value={room.unit_count}/><Field label="Max adults" type="number" bind:value={room.max_adults}/><Field label="Max children" type="number" bind:value={room.max_children}/><Field label="Max guests" type="number" bind:value={room.max_guests}/></div><Text label="Short description" bind:value={room.short_description}/><Chips label="Bed types" options={BED_TYPES} selected={room.bed_types??[]} onToggle={(x)=>{room.bed_types=(room.bed_types??[]).includes(x)?room.bed_types.filter((a:string)=>a!==x):[...(room.bed_types??[]),x];details=details}}/><Chips label="Views" options={ROOM_VIEWS} selected={room.views??[]} onToggle={(x)=>{room.views=(room.views??[]).includes(x)?room.views.filter((a:string)=>a!==x):[...(room.views??[]),x];details=details}}/><Chips label="Room amenities" options={roomAmenities} selected={room.amenities??[]} onToggle={(x)=>{room.amenities=(room.amenities??[]).includes(x)?room.amenities.filter((a:string)=>a!==x):[...(room.amenities??[]),x];details=details}}/><RoomImages bind:images={room.images}/></Card>{/each}</Section>
          {:else if step===4}<Section title="Tour Operator Rates" note="Optional seasonal rates for quotations—not inventory management."><div class="flex flex-wrap items-center justify-between gap-3"><button class="add" type="button" on:click={addRate}><Plus size={15}/> Add season</button><Check label="Show rates publicly" bind:checked={form.show_rates_publicly}/></div>{#each details.rates as rate,i}<Card title={rate.season_name||rate.season_type||`Season ${i+1}`} remove={()=>removeAt('rates',i)}><div class="grid gap-3 md:grid-cols-3"><Select label="Season type" bind:value={rate.season_type} options={SEASON_TYPES}/><Field label="Custom season name (optional)" bind:value={rate.season_name}/><Field label="Valid from" type="date" bind:value={rate.valid_from}/><Field label="Valid until" type="date" bind:value={rate.valid_until}/><Field label="Currency" bind:value={rate.currency}/><Select label="Pricing basis" bind:value={rate.pricing_basis} options={PRICING_BASES}/><Select label="Meal plan" bind:value={rate.meal_plan} options={MEAL_PLANS}/><Field label="Rack rate" type="number" bind:value={rate.rack_rate}/><Field label="Contracted / net rate" type="number" bind:value={rate.net_rate}/><Field label="Single rate" type="number" bind:value={rate.single_rate}/><Field label="Double rate" type="number" bind:value={rate.double_rate}/><Field label="Triple rate" type="number" bind:value={rate.triple_rate}/><Field label="Child rate" type="number" bind:value={rate.child_rate}/><Field label="Single supplement" type="number" bind:value={rate.single_supplement}/></div></Card>{/each}</Section>
          {:else if step===5}<Section title="Amenities & Experiences" note="Controlled attributes only; free text is reserved for traveler notes."><p class="text-sm text-ink/60">Property amenities are selected in the Gallery step from the reusable amenity library.</p><Chips label="Experiences" options={experienceOptions.map(x=>x.name)} selected={experienceOptions.filter(x=>details.experience_ids.includes(x.id)).map(x=>x.name)} onToggle={toggleExperience}/><div class="grid gap-3 md:grid-cols-2"><Check label="Children allowed" bind:checked={form.children_allowed}/><Field label="Minimum child age" type="number" bind:value={form.minimum_child_age}/><Check label="Family friendly" bind:checked={form.family_friendly}/><Check label="Honeymoon friendly" bind:checked={form.honeymoon_friendly}/><Check label="Wheelchair accessible" bind:checked={form.wheelchair_accessible}/></div><div class="grid gap-3 md:grid-cols-3"><Select label="Accessibility" bind:value={form.accessibility} options={ACCESSIBILITY}/><Select label="Electricity" bind:value={form.electricity_availability} options={ELECTRICITY}/><Select label="Wi-Fi" bind:value={form.wifi_availability} options={WIFI}/></div><Chips label="Mobile networks" options={MOBILE_NETWORKS} selected={form.mobile_networks} onToggle={(x)=>toggle('mobile_networks',x)}/><Text label="Arrival instructions" bind:value={form.arrival_instructions}/><Text label="Traveler notes" bind:value={form.traveler_notes}/><div class="grid gap-4 md:grid-cols-2"><Repeater title="Included" items={details.inclusions.filter((x:any)=>x.is_included)} add={()=>addItem(true)} remove={(i)=>removeInclusion(true,i)} field="title"/><Repeater title="Excluded" items={details.inclusions.filter((x:any)=>!x.is_included)} add={()=>addItem(false)} remove={(i)=>removeInclusion(false,i)} field="title"/></div></Section>
          {:else if step===6}<Section title="Gallery & Images" note="Choose optimized media-library assets, order the gallery, and set its cover."><div class="grid gap-4 md:grid-cols-3"><MediaPicker label="Hero image" uploadFolder="lodges" bind:value={form.hero_image_url}/><MediaPicker label="Card image" uploadFolder="lodges" bind:value={form.image_url}/><MediaPicker label="Mobile hero" uploadFolder="lodges" bind:value={form.mobile_hero_image_url}/></div><AdminLodgeMedia bind:this={mediaEditor}/></Section>
          {:else if step===7}<Section title="Supplier Information" note="Compact, admin-only commercial contacts. Never returned publicly."><div class="grid gap-3 md:grid-cols-2"><Select label="Supplier / company" bind:value={details.supplier.supplier_id} options={supplierOptions.map(x=>x.id)} labels={Object.fromEntries(supplierOptions.map(x=>[x.id,x.name]))}/><Field label="New supplier (only if not listed)" bind:value={details.supplier.new_supplier_name}/><Select label="Supplier preference" bind:value={details.supplier.supplier_preference} options={SUPPLIER_PREFERENCES}/><Field label="Reservation contact" bind:value={details.supplier.contact_person}/><Field label="Reservation email" bind:value={details.supplier.reservation_email}/><Field label="Phone / WhatsApp" bind:value={details.supplier.phone_whatsapp}/><Field label="Commission %" type="number" bind:value={details.supplier.commission_percent}/><Field label="Contract start" type="date" bind:value={details.supplier.contract_start}/><Field label="Contract end" type="date" bind:value={details.supplier.contract_end}/><Field label="Last inspection" type="date" bind:value={details.supplier.last_inspection_date}/></div><Text label="Payment terms" bind:value={details.supplier.payment_terms}/><Text label="Cancellation terms" bind:value={details.supplier.cancellation_terms}/><Text label="Internal notes" bind:value={details.supplier.internal_notes}/><MediaPicker label="Contract / document" uploadFolder="lodge-contracts" bind:value={details.supplier.contract_document_url}/><Check label="Personally inspected" bind:checked={details.supplier.personally_inspected}/></Section>
          {:else if step===8}<Section title="Related Tours & Destinations" note="References existing records; nothing is duplicated."><Chips label="Related destinations" options={destinations.filter(x=>x.value).map(x=>x.label)} selected={destinations.filter(x=>details.destination_ids.includes(x.value)).map(x=>x.label)} onToggle={toggleDestination}/><Chips label={`Used in ${details.tour_ids.length} Tours`} options={tours.map(x=>x.title)} selected={tours.filter(x=>details.tour_ids.includes(x.id)).map(x=>x.title)} onToggle={(name)=>toggleRelation('tour_ids',tours,'title',name)}/><Chips label="Similar / alternative properties" options={lodges.map(x=>x.name)} selected={lodges.filter(x=>details.alternative_ids.includes(x.id)).map(x=>x.name)} onToggle={(name)=>toggleRelation('alternative_ids',lodges,'name',name)}/></Section>
          {:else if step===9}<Section title="SEO" note="Defaults come from the property name and short description; override only when useful."><Field label="URL slug" bind:value={form.slug}/><Field label="SEO title" bind:value={form.seo_title}/><Text label="Meta description" bind:value={form.meta_description}/><MediaPicker label="Social sharing image" uploadFolder="lodges" bind:value={form.social_image_url}/><Check label="Allow search-engine indexing" bind:checked={form.indexable}/></Section>
          {:else}<Section title="Review & Publish" note="Check the important signals before publishing."><div class="grid gap-3 md:grid-cols-3">{#each [['Basics',form.name&&form.destination_id],['Photography',form.hero_image_url&&form.image_url],['Travel profile',form.best_for.length&&form.setting],['Rooms',details.rooms.length],['Rates',details.rates.length],['Relationships',details.destination_ids.length||form.destination_id]] as item}<div class={`rounded-xl border p-4 ${item[1]?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}><p class="font-bold text-heading">{item[0]}</p><p class="mt-1 text-xs text-ink/60">{item[1]?'Ready':'Needs attention'}</p></div>{/each}</div><Select label="Publishing status" bind:value={form.status} options={['draft','published','archived']} labels={{draft:'Draft',published:'Published',archived:'Hidden'}}/></Section>{/if}
        </div>
      </div>
      <footer class="flex shrink-0 items-center gap-2 border-t border-ink/10 bg-surface p-3 md:px-6"><button class="btn secondary" type="button" disabled={step===0} on:click={()=>step--}><ArrowLeft size={15}/> Previous</button><span class="hidden text-xs text-ink/45 md:block">Draft auto-saved locally</span><div class="ml-auto flex gap-2"><button class="btn secondary" type="button" disabled={saving} on:click={()=>save(true)}><Save size={15}/> Save & Exit</button>{#if step<steps.length-1}<button class="btn primary" type="button" on:click={()=>step++}>Next <ArrowRight size={15}/></button>{:else}<button class="btn primary" type="submit" disabled={saving}>{saving?'Saving…':form.status==='published'?'Publish':'Save Draft'}</button>{/if}</div></footer>
    </form>
  </div>
</div>

<style>
  .btn,.add{display:inline-flex;align-items:center;justify-content:center;gap:.4rem;height:2.65rem;border-radius:.55rem;padding:0 1rem;font-size:.83rem;font-weight:700}.primary{background:rgb(var(--c-goldfinch-gold));color:rgb(var(--c-heading))}.secondary{border:1px solid rgb(var(--c-ink)/.12);background:rgb(var(--c-surface));color:rgb(var(--c-ink))}.add{border:1px dashed rgb(var(--c-forest)/.35);color:rgb(var(--c-forest));margin-bottom:1rem}.btn:disabled{opacity:.45}
</style>
